// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! The oracle truth-table schema and its shared assertions (ADR 0002).
//!
//! Truth tables are JSON committed under each adapter's `tests/data/`,
//! generated by pinned oracles (rasterio for COG, h5py for the virtual
//! source). Every table shares the same per-window pixel-identity block
//! ([`PixelCase`]); per-source keys (file/band, array, overview factor)
//! stay in the consuming test via `#[serde(flatten)]`:
//!
//! ```ignore
//! #[derive(serde::Deserialize)]
//! struct Case {
//!     file: String,
//!     band: u32,
//!     #[serde(flatten)]
//!     px: swath_testsupport::truth::PixelCase,
//! }
//! let truth: Truth<Case> = truth::load(include_str!("data/window_truth.json"));
//! ```

use serde::Deserialize;
use serde::de::DeserializeOwned;
use sha2::{Digest, Sha256};
use swath_core::raster::WindowRequest;
use swath_core::source::{PixelBuffer, WindowData};

/// A truth table: the oracle's list of cases.
#[derive(Deserialize)]
pub struct Truth<C> {
    /// One entry per (asset, window) the oracle read.
    pub cases: Vec<C>,
}

/// Parses a committed truth table (pass `include_str!` of the JSON).
pub fn load<C: DeserializeOwned>(raw: &str) -> Truth<C> {
    serde_json::from_str(raw).expect("truth-table JSON parses")
}

/// A pixel window in grid coordinates, as the oracle records it.
#[derive(Deserialize, PartialEq, Eq, Debug, Clone, Copy)]
pub struct Win {
    /// Leftmost column of the window.
    pub col_off: u64,
    /// Topmost row of the window.
    pub row_off: u64,
    /// Window width in pixels.
    pub width: u64,
    /// Window height in pixels.
    pub height: u64,
}

impl From<Win> for WindowRequest {
    fn from(w: Win) -> Self {
        Self {
            col_off: w.col_off,
            row_off: w.row_off,
            width: w.width,
            height: w.height,
        }
    }
}

/// The per-window pixel-identity block every truth table shares. Comparison
/// against the oracle is EXACT: the SHA-256 of the little-endian pixel
/// bytes must match byte-for-byte; the redundant statistics exist because
/// their failure output is far more diagnostic than a hash mismatch.
#[derive(Deserialize)]
pub struct PixelCase {
    /// The oracle's name for this window shape (e.g. `full`, `one_pixel`).
    pub window_name: String,
    /// The window as requested (may extend out of bounds).
    pub requested: Win,
    /// The request clipped to the grid — what a read must return.
    pub clipped: Win,
    /// The numpy dtype string of the source samples.
    pub dtype: String,
    /// The nodata sentinel value.
    pub nodata: f64,
    /// How many samples in the clipped window equal the sentinel.
    pub nodata_count: u64,
    /// Sum of all non-sentinel samples (widened to i64).
    pub valid_sum: i64,
    /// The first (up to) 8 samples in row-major order.
    pub first8: Vec<i64>,
    /// The last (up to) 8 samples in row-major order.
    pub last8: Vec<i64>,
    /// SHA-256 hex digest of the samples' little-endian bytes.
    pub sha256_le: String,
}

/// Samples widened to i64 for sum/first/last comparisons (all committed
/// fixture dtypes are integral; the truth tables store them as JSON
/// integers).
pub fn widened(pixels: &PixelBuffer) -> Vec<i64> {
    match pixels {
        PixelBuffer::UInt8(v) => v.iter().map(|&s| i64::from(s)).collect(),
        PixelBuffer::Int16(v) => v.iter().map(|&s| i64::from(s)).collect(),
        other => panic!("unexpected pixel dtype in fixtures: {:?}", other.dtype()),
    }
}

/// Asserts the shared pixel-identity block of `case` against a read's
/// `WindowData`: clipped window, nodata sentinel, pixel count, exact
/// byte-for-byte hash, and the diagnostic statistics. Per-source checks
/// (dtype mapping, grid, provenance) stay in the consuming test.
#[allow(
    clippy::cast_possible_truncation,
    reason = "nodata sentinels are exact small integers"
)]
pub fn assert_pixels_match(name: &str, case: &PixelCase, wd: &WindowData) {
    assert_eq!(wd.window, case.clipped.into(), "{name}: clipped window");
    assert_eq!(wd.nodata, Some(case.nodata), "{name}: nodata sentinel");
    let expected_len = usize::try_from(wd.window.width * wd.window.height).unwrap();
    assert_eq!(wd.pixels.len(), expected_len, "{name}: pixel count");

    // EXACT pixel equality with the oracle: hash of raw little-endian bytes.
    let hash = format!("{:x}", Sha256::digest(wd.pixels.to_le_bytes()));
    assert_eq!(
        hash, case.sha256_le,
        "{name}: pixel bytes differ from the oracle"
    );

    // Redundant with the hash, but failure output is far more diagnostic.
    let samples = widened(&wd.pixels);
    let sentinel = case.nodata as i64;
    let nodata_count = samples.iter().filter(|&&s| s == sentinel).count() as u64;
    let valid_sum: i64 = samples.iter().filter(|&&s| s != sentinel).sum();
    assert_eq!(nodata_count, case.nodata_count, "{name}: nodata count");
    assert_eq!(valid_sum, case.valid_sum, "{name}: valid-pixel sum");
    let take8 = samples.len().min(8);
    assert_eq!(&samples[..take8], &case.first8[..], "{name}: first pixels");
    assert_eq!(
        &samples[samples.len() - take8..],
        &case.last8[..],
        "{name}: last pixels"
    );
}
