// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Overview reads (`ReadLevel::Overview`) against the GDAL truth table
//! (issue #38, ADR 0002).
//!
//! `tests/data/overview_truth.json` is generated by
//! `tests/oracle/window_truth.py` (pinned rasterio) from the immutable HLS
//! fixtures' embedded ×2 overview IFDs, read EXPLICITLY
//! (`rasterio.open(..., overview_level=0)`) so the hashed bytes are the
//! overview IFD's stored samples — the same bytes async-tiff decodes.
//! Requests are in full-resolution coordinates (the port's coordinate-space
//! contract); the truth table pins the rounding contract's clipped
//! overview-grid window, the overview grid itself (dims + transform), and
//! the exact pixel bytes. Provenance must be *real* overview I/O: ranges
//! within the file, `bytes_read` their sum, and the whole overview read
//! cheaper than the equivalent full-resolution read.

mod common;

use sha2::{Digest, Sha256};
use swath_core::raster::{AssetRef, WindowRequest};
use swath_core::source::{
    BandSelection, PixelBuffer, RasterSource, ReadLevel, SourceError, WindowData,
};

#[derive(serde::Deserialize)]
struct Truth {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    file: String,
    band: u32,
    factor: u32,
    window_name: String,
    requested: Win,
    clipped: Win,
    grid: Grid,
    dtype: String,
    nodata: f64,
    nodata_count: u64,
    valid_sum: i64,
    first8: Vec<i64>,
    last8: Vec<i64>,
    sha256_le: String,
}

#[derive(serde::Deserialize, PartialEq, Eq, Debug, Clone, Copy)]
struct Win {
    col_off: u64,
    row_off: u64,
    width: u64,
    height: u64,
}

/// The overview grid rasterio reports for an `overview_level=` open:
/// dimensions plus the affine in rasterio order (a, b, c, d, e, f).
#[derive(serde::Deserialize)]
struct Grid {
    width: u64,
    height: u64,
    transform: [f64; 6],
}

impl From<Win> for WindowRequest {
    fn from(w: Win) -> Self {
        Self {
            col_off: w.col_off,
            row_off: w.row_off,
            width: w.width,
            height: w.height,
        }
    }
}

fn truth() -> Truth {
    let raw = include_str!("data/overview_truth.json");
    serde_json::from_str(raw).expect("overview_truth.json parses")
}

fn widened(pixels: &PixelBuffer) -> Vec<i64> {
    match pixels {
        PixelBuffer::UInt8(v) => v.iter().map(|&s| i64::from(s)).collect(),
        PixelBuffer::Int16(v) => v.iter().map(|&s| i64::from(s)).collect(),
        other => panic!("unexpected pixel dtype in fixtures: {:?}", other.dtype()),
    }
}

#[allow(
    clippy::cast_possible_truncation,
    reason = "nodata sentinels are exact small integers"
)]
#[allow(clippy::float_cmp, reason = "grid transform round-trip must be exact")]
fn check_case(case: &Case, wd: &WindowData) {
    let name = format!("{}/{}", case.file, case.window_name);

    // The rounding contract: full-res request covered onto the overview
    // grid, clipped — the returned window is in overview coordinates.
    assert_eq!(wd.window, case.clipped.into(), "{name}: clipped window");

    // The grid actually read is the overview IFD's: real dimensions and
    // the exact-ratio-scaled geotransform rasterio reports for the same
    // overview open. `overview_levels` is empty — an overview grid is not
    // itself overviewed.
    assert_eq!(wd.grid.width, case.grid.width, "{name}: grid width");
    assert_eq!(wd.grid.height, case.grid.height, "{name}: grid height");
    let [pw, rr, ox, cr, ph, oy] = case.grid.transform;
    assert_eq!(wd.grid.transform.pixel_width, pw, "{name}: pixel_width");
    assert_eq!(wd.grid.transform.row_rotation, rr, "{name}: row_rotation");
    assert_eq!(wd.grid.transform.origin_x, ox, "{name}: origin_x");
    assert_eq!(wd.grid.transform.col_rotation, cr, "{name}: col_rotation");
    assert_eq!(wd.grid.transform.pixel_height, ph, "{name}: pixel_height");
    assert_eq!(wd.grid.transform.origin_y, oy, "{name}: origin_y");
    assert!(
        wd.grid.overview_levels.is_empty(),
        "{name}: an overview grid must report no overviews of its own"
    );
    assert_eq!(wd.grid.nodata, Some(case.nodata), "{name}: grid nodata");

    assert_eq!(
        wd.dtype(),
        common::dtype_from_str(&case.dtype),
        "{name}: dtype"
    );
    assert_eq!(wd.nodata, Some(case.nodata), "{name}: nodata sentinel");
    let expected_len = usize::try_from(wd.window.width * wd.window.height).unwrap();
    assert_eq!(wd.pixels.len(), expected_len, "{name}: pixel count");

    // EXACT pixel equality with GDAL's explicit overview read.
    let hash = format!("{:x}", Sha256::digest(wd.pixels.to_le_bytes()));
    assert_eq!(hash, case.sha256_le, "{name}: pixel bytes differ from GDAL");

    // Redundant with the hash, but failure output is far more diagnostic.
    let samples = widened(&wd.pixels);
    let sentinel = case.nodata as i64;
    let nodata_count = samples.iter().filter(|&&s| s == sentinel).count() as u64;
    let valid_sum: i64 = samples.iter().filter(|&&s| s != sentinel).sum();
    assert_eq!(nodata_count, case.nodata_count, "{name}: nodata count");
    assert_eq!(valid_sum, case.valid_sum, "{name}: valid-pixel sum");
    let take8 = samples.len().min(8);
    assert_eq!(&samples[..take8], &case.first8[..], "{name}: first pixels");
    assert_eq!(
        &samples[samples.len() - take8..],
        &case.last8[..],
        "{name}: last pixels"
    );

    // Provenance is real overview I/O: non-empty, in-bounds, bytes_read is
    // the sum, and the fixtures' single 256×256 overview tile means every
    // window touches exactly one range.
    let file_len = common::file_len(&case.file);
    assert!(
        !wd.provenance.is_empty(),
        "{name}: provenance must be non-empty"
    );
    for p in &wd.provenance {
        assert_eq!(p.path, case.file, "{name}: provenance path");
        assert!(p.length > 0, "{name}: zero-length provenance range");
        assert!(
            p.offset + p.length <= file_len,
            "{name}: provenance range {}+{} exceeds file size {file_len}",
            p.offset,
            p.length
        );
    }
    let sum: u64 = wd.provenance.iter().map(|p| p.length).sum();
    assert_eq!(wd.bytes_read, sum, "{name}: bytes_read != sum of ranges");
    assert_eq!(
        wd.provenance.len(),
        1,
        "{name}: the fixtures' overview is a single 256px tile"
    );
}

#[tokio::test]
async fn overview_windows_match_gdal_truth_table_exactly() {
    let truth = truth();
    assert_eq!(truth.cases.len(), 25, "5 fixtures x 5 windows");
    let source = common::local_source();
    for case in &truth.cases {
        let wd = source
            .read_window(
                &AssetRef::new(&case.file),
                case.requested.into(),
                BandSelection::Single(case.band),
                ReadLevel::Overview {
                    factor: case.factor,
                },
            )
            .await
            .unwrap_or_else(|e| panic!("{}/{}: {e}", case.file, case.window_name));
        check_case(case, &wd);
    }
}

#[tokio::test]
async fn overview_local_and_memory_stores_agree() {
    let truth = truth();
    let local = common::local_source();
    let memory = common::memory_source().await;
    for case in &truth.cases {
        let asset = AssetRef::new(&case.file);
        let band = BandSelection::Single(case.band);
        let level = ReadLevel::Overview {
            factor: case.factor,
        };
        let a = local
            .read_window(&asset, case.requested.into(), band, level)
            .await
            .expect("local read");
        let b = memory
            .read_window(&asset, case.requested.into(), band, level)
            .await
            .expect("memory read");
        assert_eq!(
            a, b,
            "{}/{}: local-file and in-memory reads disagree",
            case.file, case.window_name
        );
    }
}

/// The point of overviews: the same full coverage costs fewer bytes. The
/// full-window overview read must fetch strictly less than the full-window
/// full-resolution read (the ×2 overview holds a quarter of the pixels;
/// assert a loose 2x reduction so compression noise can't flake it).
#[tokio::test]
async fn overview_reads_fetch_fewer_bytes_than_full_res() {
    let source = common::local_source();
    let asset = AssetRef::new("hlss30-t13sdd-2024158-b04.tif");
    let window = WindowRequest {
        col_off: 0,
        row_off: 0,
        width: 512,
        height: 512,
    };
    let band = BandSelection::Single(0);
    let full = source
        .read_window(&asset, window, band, ReadLevel::FullRes)
        .await
        .expect("full-res read");
    let overview = source
        .read_window(&asset, window, band, ReadLevel::Overview { factor: 2 })
        .await
        .expect("overview read");
    assert!(
        overview.bytes_read * 2 <= full.bytes_read,
        "overview read ({} bytes) should cost well under half the \
         full-res read ({} bytes)",
        overview.bytes_read,
        full.bytes_read,
    );
}

#[tokio::test]
async fn missing_overview_level_is_a_clear_error() {
    let source = common::local_source();
    let asset = AssetRef::new("hlss30-t13sdd-2024158-b04.tif");
    let err = source
        .read_window(
            &asset,
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(0),
            ReadLevel::Overview { factor: 4 },
        )
        .await
        .expect_err("the fixtures carry only a x2 overview");
    match err {
        SourceError::OverviewNotFound {
            factor, available, ..
        } => {
            assert_eq!(factor, 4);
            assert_eq!(available, vec![2]);
        }
        other => panic!("expected OverviewNotFound, got {other:?}"),
    }
}

#[tokio::test]
async fn out_of_bounds_overview_window_reads_nothing() {
    let source = common::local_source();
    let wd = source
        .read_window(
            &AssetRef::new("hlss30-t13sdd-2024158-b04.tif"),
            WindowRequest {
                col_off: 600,
                row_off: 700,
                width: 10,
                height: 10,
            },
            BandSelection::Single(0),
            ReadLevel::Overview { factor: 2 },
        )
        .await
        .expect("out-of-bounds read clips to empty");
    assert!(wd.window.is_empty(), "window must clip to empty");
    assert!(wd.pixels.is_empty(), "no pixels for an empty window");
    assert!(wd.provenance.is_empty(), "no I/O for an empty window");
    assert_eq!(wd.bytes_read, 0);
    assert_eq!(wd.grid.width, 256, "empty result still reports the grid");
}
