// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Overview reads (`ReadLevel::Overview`) against the GDAL truth table
//! (issue #38, ADR 0002).
//!
//! `tests/data/overview_truth.json` is generated by
//! `tests/oracle/window_truth.py` (pinned rasterio) from the immutable HLS
//! fixtures' embedded ×2 overview IFDs, read EXPLICITLY
//! (`rasterio.open(..., overview_level=0)`) so the hashed bytes are the
//! overview IFD's stored samples — the same bytes async-tiff decodes.
//! Requests are in full-resolution coordinates (the port's coordinate-space
//! contract); the truth table pins the rounding contract's clipped
//! overview-grid window, the overview grid itself (dims + transform), and
//! the exact pixel bytes. Provenance must be *real* overview I/O: ranges
//! within the file, `bytes_read` their sum, and the whole overview read
//! cheaper than the equivalent full-resolution read.

mod common;

use swath_core::raster::{AssetRef, WindowRequest};
use swath_core::source::{BandSelection, RasterSource, ReadLevel, SourceError, WindowData};
use swath_testsupport::truth::{self, PixelCase, Truth};

/// Per-source keys on top of the shared pixel-identity block.
#[derive(serde::Deserialize)]
struct Case {
    file: String,
    band: u32,
    factor: u32,
    grid: Grid,
    #[serde(flatten)]
    px: PixelCase,
}

/// The overview grid rasterio reports for an `overview_level=` open:
/// dimensions plus the affine in rasterio order (a, b, c, d, e, f).
#[derive(serde::Deserialize)]
struct Grid {
    width: u64,
    height: u64,
    transform: [f64; 6],
}

fn truth() -> Truth<Case> {
    truth::load(include_str!("data/overview_truth.json"))
}

#[allow(clippy::float_cmp, reason = "grid transform round-trip must be exact")]
fn check_case(case: &Case, wd: &WindowData) {
    let name = format!("{}/{}", case.file, case.px.window_name);

    // The grid actually read is the overview IFD's: real dimensions and
    // the exact-ratio-scaled geotransform rasterio reports for the same
    // overview open. `overview_levels` is empty — an overview grid is not
    // itself overviewed.
    assert_eq!(wd.grid.width, case.grid.width, "{name}: grid width");
    assert_eq!(wd.grid.height, case.grid.height, "{name}: grid height");
    let [pw, rr, ox, cr, ph, oy] = case.grid.transform;
    assert_eq!(wd.grid.transform.pixel_width, pw, "{name}: pixel_width");
    assert_eq!(wd.grid.transform.row_rotation, rr, "{name}: row_rotation");
    assert_eq!(wd.grid.transform.origin_x, ox, "{name}: origin_x");
    assert_eq!(wd.grid.transform.col_rotation, cr, "{name}: col_rotation");
    assert_eq!(wd.grid.transform.pixel_height, ph, "{name}: pixel_height");
    assert_eq!(wd.grid.transform.origin_y, oy, "{name}: origin_y");
    assert!(
        wd.grid.overview_levels.is_empty(),
        "{name}: an overview grid must report no overviews of its own"
    );
    assert_eq!(wd.grid.nodata, Some(case.px.nodata), "{name}: grid nodata");

    assert_eq!(
        wd.dtype(),
        common::dtype_from_str(&case.px.dtype),
        "{name}: dtype"
    );
    // The rounding contract: full-res request covered onto the overview
    // grid, clipped — the returned window is in overview coordinates; then
    // EXACT pixel equality with GDAL's explicit overview read.
    truth::assert_pixels_match(&name, &case.px, wd);

    // Provenance is real overview I/O: non-empty, in-bounds, bytes_read is
    // the sum, and the fixtures' single 256×256 overview tile means every
    // window touches exactly one range.
    let file_len = common::file_len(&case.file);
    assert!(
        !wd.provenance.is_empty(),
        "{name}: provenance must be non-empty"
    );
    for p in &wd.provenance {
        assert_eq!(p.path, case.file, "{name}: provenance path");
        assert!(p.length > 0, "{name}: zero-length provenance range");
        assert!(
            p.offset + p.length <= file_len,
            "{name}: provenance range {}+{} exceeds file size {file_len}",
            p.offset,
            p.length
        );
    }
    let sum: u64 = wd.provenance.iter().map(|p| p.length).sum();
    assert_eq!(wd.bytes_read, sum, "{name}: bytes_read != sum of ranges");
    assert_eq!(
        wd.provenance.len(),
        1,
        "{name}: the fixtures' overview is a single 256px tile"
    );
}

#[tokio::test]
async fn overview_windows_match_gdal_truth_table_exactly() {
    let truth = truth();
    assert_eq!(truth.cases.len(), 25, "5 fixtures x 5 windows");
    let source = common::local_source();
    for case in &truth.cases {
        let wd = source
            .read_window(
                &AssetRef::new(&case.file),
                case.px.requested.into(),
                BandSelection::Single(case.band),
                ReadLevel::Overview {
                    factor: case.factor,
                },
            )
            .await
            .unwrap_or_else(|e| panic!("{}/{}: {e}", case.file, case.px.window_name));
        check_case(case, &wd);
    }
}

#[tokio::test]
async fn overview_local_and_memory_stores_agree() {
    let truth = truth();
    let local = common::local_source();
    let memory = common::memory_source().await;
    for case in &truth.cases {
        let asset = AssetRef::new(&case.file);
        let band = BandSelection::Single(case.band);
        let level = ReadLevel::Overview {
            factor: case.factor,
        };
        let a = local
            .read_window(&asset, case.px.requested.into(), band, level)
            .await
            .expect("local read");
        let b = memory
            .read_window(&asset, case.px.requested.into(), band, level)
            .await
            .expect("memory read");
        assert_eq!(
            a, b,
            "{}/{}: local-file and in-memory reads disagree",
            case.file, case.px.window_name
        );
    }
}

/// The point of overviews: the same full coverage costs fewer bytes. The
/// full-window overview read must fetch strictly less than the full-window
/// full-resolution read (the ×2 overview holds a quarter of the pixels;
/// assert a loose 2x reduction so compression noise can't flake it).
#[tokio::test]
async fn overview_reads_fetch_fewer_bytes_than_full_res() {
    let source = common::local_source();
    let asset = AssetRef::new("hlss30-t13sdd-2024158-b04.tif");
    let window = WindowRequest {
        col_off: 0,
        row_off: 0,
        width: 512,
        height: 512,
    };
    let band = BandSelection::Single(0);
    let full = source
        .read_window(&asset, window, band, ReadLevel::FullRes)
        .await
        .expect("full-res read");
    let overview = source
        .read_window(&asset, window, band, ReadLevel::Overview { factor: 2 })
        .await
        .expect("overview read");
    assert!(
        overview.bytes_read * 2 <= full.bytes_read,
        "overview read ({} bytes) should cost well under half the \
         full-res read ({} bytes)",
        overview.bytes_read,
        full.bytes_read,
    );
}

#[tokio::test]
async fn missing_overview_level_is_a_clear_error() {
    let source = common::local_source();
    let asset = AssetRef::new("hlss30-t13sdd-2024158-b04.tif");
    let err = source
        .read_window(
            &asset,
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(0),
            ReadLevel::Overview { factor: 4 },
        )
        .await
        .expect_err("the fixtures carry only a x2 overview");
    match err {
        SourceError::OverviewNotFound {
            factor, available, ..
        } => {
            assert_eq!(factor, 4);
            assert_eq!(available, vec![2]);
        }
        other => panic!("expected OverviewNotFound, got {other:?}"),
    }
}

#[tokio::test]
async fn out_of_bounds_overview_window_reads_nothing() {
    let source = common::local_source();
    let wd = source
        .read_window(
            &AssetRef::new("hlss30-t13sdd-2024158-b04.tif"),
            WindowRequest {
                col_off: 600,
                row_off: 700,
                width: 10,
                height: 10,
            },
            BandSelection::Single(0),
            ReadLevel::Overview { factor: 2 },
        )
        .await
        .expect("out-of-bounds read clips to empty");
    assert!(wd.window.is_empty(), "window must clip to empty");
    assert!(wd.pixels.is_empty(), "no pixels for an empty window");
    assert!(wd.provenance.is_empty(), "no I/O for an empty window");
    assert_eq!(wd.bytes_read, 0);
    assert_eq!(wd.grid.width, 256, "empty result still reports the grid");
}
