// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! `read_window()` against the GDAL truth table (issue #22, ADR 0002).
//!
//! `tests/data/window_truth.json` is generated by
//! `tests/oracle/window_truth.py` (pinned rasterio) from the immutable HLS
//! fixtures. Comparison is EXACT: the SHA-256 of the little-endian pixel
//! bytes must match GDAL's read byte-for-byte. Provenance is validated as
//! *real* I/O: ranges lie within the file, `bytes_read` is their sum, and
//! tile-touch counts match the window geometry.

mod common;

use swath_core::raster::{AssetRef, WindowRequest};
use swath_core::source::{BandSelection, RasterSource, ReadLevel, SourceError, WindowData};
use swath_testsupport::truth::{self, PixelCase, Truth};

/// Per-source keys on top of the shared pixel-identity block.
#[derive(serde::Deserialize)]
struct Case {
    file: String,
    band: u32,
    #[serde(flatten)]
    px: PixelCase,
}

fn truth() -> Truth<Case> {
    truth::load(include_str!("data/window_truth.json"))
}

fn check_case(case: &Case, wd: &WindowData) {
    let name = format!("{}/{}", case.file, case.px.window_name);

    assert_eq!(
        wd.dtype(),
        common::dtype_from_str(&case.px.dtype),
        "{name}: dtype"
    );
    truth::assert_pixels_match(&name, &case.px, wd);

    // Provenance is real I/O: non-empty, in-bounds, and bytes_read is the sum.
    let file_len = common::file_len(&case.file);
    assert!(
        !wd.provenance.is_empty(),
        "{name}: provenance must be non-empty"
    );
    for p in &wd.provenance {
        assert_eq!(p.path, case.file, "{name}: provenance path");
        assert!(p.length > 0, "{name}: zero-length provenance range");
        assert!(
            p.offset + p.length <= file_len,
            "{name}: provenance range {}+{} exceeds file size {file_len}",
            p.offset,
            p.length
        );
    }
    let sum: u64 = wd.provenance.iter().map(|p| p.length).sum();
    assert_eq!(wd.bytes_read, sum, "{name}: bytes_read != sum of ranges");

    // Tile-touch geometry (256px internal tiles, 512px grid): the full
    // window covers all four tiles, the interior window crosses both seams
    // (four tiles), and the 1px window touches exactly one.
    match case.px.window_name.as_str() {
        "full" | "interior" => {
            assert_eq!(wd.provenance.len(), 4, "{name}: expected all four tiles");
        }
        "one_pixel" | "nodata_edge" | "oob_clipped" => {
            assert_eq!(wd.provenance.len(), 1, "{name}: expected exactly one tile");
        }
        other => panic!("unknown window case {other}"),
    }
}

#[tokio::test]
async fn windows_match_gdal_truth_table_exactly() {
    let truth = truth();
    assert_eq!(truth.cases.len(), 25, "5 fixtures x 5 windows");
    let source = common::local_source();
    for case in &truth.cases {
        let wd = source
            .read_window(
                &AssetRef::new(&case.file),
                case.px.requested.into(),
                BandSelection::Single(case.band),
                ReadLevel::FullRes,
            )
            .await
            .unwrap_or_else(|e| panic!("{}/{}: {e}", case.file, case.px.window_name));
        check_case(case, &wd);
    }
}

#[tokio::test]
async fn local_and_memory_stores_agree() {
    let truth = truth();
    let local = common::local_source();
    let memory = common::memory_source().await;
    for case in &truth.cases {
        let asset = AssetRef::new(&case.file);
        let band = BandSelection::Single(case.band);
        let a = local
            .read_window(&asset, case.px.requested.into(), band, ReadLevel::FullRes)
            .await
            .expect("local read");
        let b = memory
            .read_window(&asset, case.px.requested.into(), band, ReadLevel::FullRes)
            .await
            .expect("memory read");
        assert_eq!(
            a, b,
            "{}/{}: local-file and in-memory reads disagree",
            case.file, case.px.window_name
        );
    }
}

#[tokio::test]
async fn fully_out_of_bounds_window_reads_nothing() {
    let source = common::local_source();
    let wd = source
        .read_window(
            &AssetRef::new("hlss30-t13sdd-2024158-b04.tif"),
            WindowRequest {
                col_off: 600,
                row_off: 700,
                width: 10,
                height: 10,
            },
            BandSelection::Single(0),
            ReadLevel::FullRes,
        )
        .await
        .expect("out-of-bounds read clips to empty");
    assert!(wd.window.is_empty(), "window must clip to empty");
    assert!(wd.pixels.is_empty(), "no pixels for an empty window");
    assert!(wd.provenance.is_empty(), "no I/O for an empty window");
    assert_eq!(wd.bytes_read, 0);
}

#[tokio::test]
async fn band_out_of_range_is_rejected() {
    let source = common::local_source();
    let err = source
        .read_window(
            &AssetRef::new("hlss30-t13sdd-2024158-b04.tif"),
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(1),
            ReadLevel::FullRes,
        )
        .await
        .expect_err("band 1 of a single-band asset must fail");
    assert!(
        matches!(
            err,
            SourceError::BandOutOfRange {
                band: 1,
                band_count: 1,
                ..
            }
        ),
        "expected BandOutOfRange, got {err:?}"
    );
}
