// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! `read_window()` against the GDAL truth table (issue #22, ADR 0002).
//!
//! `tests/data/window_truth.json` is generated by
//! `tests/oracle/window_truth.py` (pinned rasterio) from the immutable HLS
//! fixtures. Comparison is EXACT: the SHA-256 of the little-endian pixel
//! bytes must match GDAL's read byte-for-byte. Provenance is validated as
//! *real* I/O: ranges lie within the file, `bytes_read` is their sum, and
//! tile-touch counts match the window geometry.

mod common;

use sha2::{Digest, Sha256};
use swath_core::raster::{AssetRef, WindowRequest};
use swath_core::source::{BandSelection, PixelBuffer, RasterSource, SourceError, WindowData};

#[derive(serde::Deserialize)]
struct Truth {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    file: String,
    band: u32,
    window_name: String,
    requested: Win,
    clipped: Win,
    dtype: String,
    nodata: f64,
    nodata_count: u64,
    valid_sum: i64,
    first8: Vec<i64>,
    last8: Vec<i64>,
    sha256_le: String,
}

#[derive(serde::Deserialize, PartialEq, Eq, Debug, Clone, Copy)]
struct Win {
    col_off: u64,
    row_off: u64,
    width: u64,
    height: u64,
}

impl From<Win> for WindowRequest {
    fn from(w: Win) -> Self {
        Self {
            col_off: w.col_off,
            row_off: w.row_off,
            width: w.width,
            height: w.height,
        }
    }
}

fn truth() -> Truth {
    let raw = include_str!("data/window_truth.json");
    serde_json::from_str(raw).expect("window_truth.json parses")
}

/// Samples widened to i64 for sum/first/last comparisons (both fixture
/// dtypes are integral; the truth table stores them as JSON integers).
fn widened(pixels: &PixelBuffer) -> Vec<i64> {
    match pixels {
        PixelBuffer::UInt8(v) => v.iter().map(|&s| i64::from(s)).collect(),
        PixelBuffer::Int16(v) => v.iter().map(|&s| i64::from(s)).collect(),
        other => panic!("unexpected pixel dtype in fixtures: {:?}", other.dtype()),
    }
}

#[allow(
    clippy::cast_possible_truncation,
    reason = "nodata sentinels are exact small integers"
)]
fn check_case(case: &Case, wd: &WindowData) {
    let name = format!("{}/{}", case.file, case.window_name);

    assert_eq!(wd.window, case.clipped.into(), "{name}: clipped window");
    assert_eq!(
        wd.dtype(),
        common::dtype_from_str(&case.dtype),
        "{name}: dtype"
    );
    assert_eq!(wd.nodata, Some(case.nodata), "{name}: nodata sentinel");
    let expected_len = usize::try_from(wd.window.width * wd.window.height).unwrap();
    assert_eq!(wd.pixels.len(), expected_len, "{name}: pixel count");

    // EXACT pixel equality with GDAL: hash of raw little-endian bytes.
    let hash = format!("{:x}", Sha256::digest(wd.pixels.to_le_bytes()));
    assert_eq!(hash, case.sha256_le, "{name}: pixel bytes differ from GDAL");

    // Redundant with the hash, but failure output is far more diagnostic.
    let samples = widened(&wd.pixels);
    let sentinel = case.nodata as i64;
    let nodata_count = samples.iter().filter(|&&s| s == sentinel).count() as u64;
    let valid_sum: i64 = samples.iter().filter(|&&s| s != sentinel).sum();
    assert_eq!(nodata_count, case.nodata_count, "{name}: nodata count");
    assert_eq!(valid_sum, case.valid_sum, "{name}: valid-pixel sum");
    let take8 = samples.len().min(8);
    assert_eq!(&samples[..take8], &case.first8[..], "{name}: first pixels");
    assert_eq!(
        &samples[samples.len() - take8..],
        &case.last8[..],
        "{name}: last pixels"
    );

    // Provenance is real I/O: non-empty, in-bounds, and bytes_read is the sum.
    let file_len = common::file_len(&case.file);
    assert!(
        !wd.provenance.is_empty(),
        "{name}: provenance must be non-empty"
    );
    for p in &wd.provenance {
        assert_eq!(p.path, case.file, "{name}: provenance path");
        assert!(p.length > 0, "{name}: zero-length provenance range");
        assert!(
            p.offset + p.length <= file_len,
            "{name}: provenance range {}+{} exceeds file size {file_len}",
            p.offset,
            p.length
        );
    }
    let sum: u64 = wd.provenance.iter().map(|p| p.length).sum();
    assert_eq!(wd.bytes_read, sum, "{name}: bytes_read != sum of ranges");

    // Tile-touch geometry (256px internal tiles, 512px grid): the full
    // window covers all four tiles, the interior window crosses both seams
    // (four tiles), and the 1px window touches exactly one.
    match case.window_name.as_str() {
        "full" | "interior" => {
            assert_eq!(wd.provenance.len(), 4, "{name}: expected all four tiles");
        }
        "one_pixel" | "nodata_edge" | "oob_clipped" => {
            assert_eq!(wd.provenance.len(), 1, "{name}: expected exactly one tile");
        }
        other => panic!("unknown window case {other}"),
    }
}

#[tokio::test]
async fn windows_match_gdal_truth_table_exactly() {
    let truth = truth();
    assert_eq!(truth.cases.len(), 25, "5 fixtures x 5 windows");
    let source = common::local_source();
    for case in &truth.cases {
        let wd = source
            .read_window(
                &AssetRef::new(&case.file),
                case.requested.into(),
                BandSelection::Single(case.band),
            )
            .await
            .unwrap_or_else(|e| panic!("{}/{}: {e}", case.file, case.window_name));
        check_case(case, &wd);
    }
}

#[tokio::test]
async fn local_and_memory_stores_agree() {
    let truth = truth();
    let local = common::local_source();
    let memory = common::memory_source().await;
    for case in &truth.cases {
        let asset = AssetRef::new(&case.file);
        let band = BandSelection::Single(case.band);
        let a = local
            .read_window(&asset, case.requested.into(), band)
            .await
            .expect("local read");
        let b = memory
            .read_window(&asset, case.requested.into(), band)
            .await
            .expect("memory read");
        assert_eq!(
            a, b,
            "{}/{}: local-file and in-memory reads disagree",
            case.file, case.window_name
        );
    }
}

#[tokio::test]
async fn fully_out_of_bounds_window_reads_nothing() {
    let source = common::local_source();
    let wd = source
        .read_window(
            &AssetRef::new("hlss30-t13sdd-2024158-b04.tif"),
            WindowRequest {
                col_off: 600,
                row_off: 700,
                width: 10,
                height: 10,
            },
            BandSelection::Single(0),
        )
        .await
        .expect("out-of-bounds read clips to empty");
    assert!(wd.window.is_empty(), "window must clip to empty");
    assert!(wd.pixels.is_empty(), "no pixels for an empty window");
    assert!(wd.provenance.is_empty(), "no I/O for an empty window");
    assert_eq!(wd.bytes_read, 0);
}

#[tokio::test]
async fn band_out_of_range_is_rejected() {
    let source = common::local_source();
    let err = source
        .read_window(
            &AssetRef::new("hlss30-t13sdd-2024158-b04.tif"),
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(1),
        )
        .await
        .expect_err("band 1 of a single-band asset must fail");
    assert!(
        matches!(
            err,
            SourceError::BandOutOfRange {
                band: 1,
                band_count: 1,
                ..
            }
        ),
        "expected BandOutOfRange, got {err:?}"
    );
}
