// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! The reusable Reproject accuracy suite (issue #23).
//!
//! Everything here is written against `&dyn Reproject` — nothing names the
//! proj4rs adapter. A future adapter (the PROJ C-binding one, per ADR 0002)
//! runs the identical suite by copying/including this module and calling
//! [`run_truth_suite`] with its own adapter and its own measured
//! [`Tolerances`]; the truth table itself
//! (`tests/data/reproject_truth.json`, generated by
//! `tests/oracle/reproject_truth.py` from pinned pyproj/PROJ) is shared
//! verbatim. That is the regression contract from issue #23: every adapter
//! passes the same suite, each with an honest, measured accuracy statement.

use swath_core::crs::Crs;
use swath_core::reproject::Reproject;

/// One truth case: `input` in the source CRS's native units must map to
/// `expected` (computed by real PROJ) in the target CRS's native units.
///
/// Each side is named by exactly one of `*_epsg` (a code) or `*_proj4`
/// (a proj string — sinusoidal has no EPSG code, issue #39); the JSON
/// grew the `*_proj4` spelling additively, so pre-#39 tables still parse.
#[derive(Debug, serde::Deserialize)]
pub(crate) struct Case {
    pub(crate) name: String,
    #[serde(default)]
    pub(crate) from_epsg: Option<u32>,
    #[serde(default)]
    pub(crate) to_epsg: Option<u32>,
    #[serde(default)]
    pub(crate) from_proj4: Option<String>,
    #[serde(default)]
    pub(crate) to_proj4: Option<String>,
    pub(crate) input: Vec<[f64; 2]>,
    pub(crate) expected: Vec<[f64; 2]>,
}

impl Case {
    /// The source CRS (exactly one spelling must be present).
    pub(crate) fn source_crs(&self) -> Crs {
        crs_of(self.from_epsg, self.from_proj4.as_deref(), &self.name)
    }

    /// The target CRS (exactly one spelling must be present).
    pub(crate) fn target_crs(&self) -> Crs {
        crs_of(self.to_epsg, self.to_proj4.as_deref(), &self.name)
    }

    /// Whether the target CRS is geographic (degrees) for tolerance
    /// selection. Every proj-string target in the table is projected.
    pub(crate) fn target_geographic(&self) -> bool {
        self.to_epsg == Some(4326)
    }
}

fn crs_of(epsg: Option<u32>, proj4: Option<&str>, name: &str) -> Crs {
    match (epsg, proj4) {
        (Some(code), None) => Crs::from_epsg(code),
        (None, Some(definition)) => Crs::from_proj4(definition),
        other => panic!("case {name}: exactly one CRS spelling required, got {other:?}"),
    }
}

/// The committed truth table with its generation provenance.
#[derive(Debug, serde::Deserialize)]
pub(crate) struct TruthTable {
    pub(crate) provenance: serde_json::Value,
    pub(crate) cases: Vec<Case>,
}

/// Loads `tests/data/reproject_truth.json`.
pub(crate) fn load_truth() -> TruthTable {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/data/reproject_truth.json"
    );
    let json = std::fs::read_to_string(path).expect("truth table readable");
    serde_json::from_str(&json).expect("truth table parses")
}

/// Per-target-kind agreement tolerances vs PROJ, in the target CRS's native
/// units. Each adapter states its own measured numbers (see the adapter's
/// crate docs for the measurement).
#[derive(Debug, Clone, Copy)]
pub(crate) struct Tolerances {
    /// Max |Δ| in degrees when the target CRS is geographic.
    pub(crate) degrees: f64,
    /// Max |Δ| in meters when the target CRS is projected.
    pub(crate) meters: f64,
}

impl Tolerances {
    fn for_target(self, case: &Case) -> f64 {
        if case.target_geographic() {
            self.degrees
        } else {
            self.meters
        }
    }
}

/// Runs every truth case against `reproject`, asserting agreement with
/// PROJ within `tol`, and returns the worst deviation observed per case
/// (for accuracy reporting). Panics with the offending case/point on any
/// violation.
pub(crate) fn run_truth_suite(reproject: &dyn Reproject, tol: Tolerances) -> Vec<(String, f64)> {
    let table = load_truth();
    assert!(
        !table.cases.is_empty(),
        "empty truth table (provenance: {})",
        table.provenance
    );
    let mut report = Vec::new();
    for case in &table.cases {
        let t = reproject
            .transformer(&case.source_crs(), &case.target_crs())
            .unwrap_or_else(|e| panic!("{}: transformer failed: {e}", case.name));
        let limit = tol.for_target(case);
        let mut worst = 0.0_f64;
        for (input, expected) in case.input.iter().zip(&case.expected) {
            let (x, y) = t
                .transform(input[0], input[1])
                .unwrap_or_else(|e| panic!("{}: transform({input:?}) failed: {e}", case.name));
            let dev = (x - expected[0]).abs().max((y - expected[1]).abs());
            assert!(
                dev <= limit,
                "{}: point {input:?} -> ({x}, {y}), PROJ says {expected:?}: \
                 deviation {dev:e} exceeds tolerance {limit:e}",
                case.name
            );
            worst = worst.max(dev);
        }
        report.push((case.name.clone(), worst));
    }
    report
}

/// Asserts the adapter's batch path is observably identical to its
/// per-point path on every truth-table input.
pub(crate) fn assert_batch_matches_per_point(reproject: &dyn Reproject) {
    let table = load_truth();
    for case in &table.cases {
        let t = reproject
            .transformer(&case.source_crs(), &case.target_crs())
            .expect("transformer");
        let mut batch: Vec<(f64, f64)> = case.input.iter().map(|p| (p[0], p[1])).collect();
        t.transform_slice(&mut batch)
            .unwrap_or_else(|e| panic!("{}: batch transform failed: {e}", case.name));
        for (input, &(bx, by)) in case.input.iter().zip(&batch) {
            let (px, py) = t
                .transform(input[0], input[1])
                .expect("per-point transform");
            assert!(
                px.to_bits() == bx.to_bits() && py.to_bits() == by.to_bits(),
                "{}: batch ({bx}, {by}) != per-point ({px}, {py}) for {input:?}",
                case.name
            );
        }
    }
}
