// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! The reusable Reproject accuracy suite (issue #23).
//!
//! Everything here is written against `&dyn Reproject` — nothing names the
//! proj4rs adapter. A future adapter (the PROJ C-binding one, per ADR 0002)
//! runs the identical suite by copying/including this module and calling
//! [`run_truth_suite`] with its own adapter and its own measured
//! [`Tolerances`]; the truth table itself
//! (`tests/data/reproject_truth.json`, generated by
//! `tests/oracle/reproject_truth.py` from pinned pyproj/PROJ) is shared
//! verbatim. That is the regression contract from issue #23: every adapter
//! passes the same suite, each with an honest, measured accuracy statement.

use swath_core::crs::Crs;
use swath_core::reproject::Reproject;

/// One truth case: `input` in `from_epsg` native units must map to
/// `expected` (computed by real PROJ) in `to_epsg` native units.
#[derive(Debug, serde::Deserialize)]
pub(crate) struct Case {
    pub(crate) name: String,
    pub(crate) from_epsg: u32,
    pub(crate) to_epsg: u32,
    pub(crate) input: Vec<[f64; 2]>,
    pub(crate) expected: Vec<[f64; 2]>,
}

/// The committed truth table with its generation provenance.
#[derive(Debug, serde::Deserialize)]
pub(crate) struct TruthTable {
    pub(crate) provenance: serde_json::Value,
    pub(crate) cases: Vec<Case>,
}

/// Loads `tests/data/reproject_truth.json`.
pub(crate) fn load_truth() -> TruthTable {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/data/reproject_truth.json"
    );
    let json = std::fs::read_to_string(path).expect("truth table readable");
    serde_json::from_str(&json).expect("truth table parses")
}

/// Per-target-kind agreement tolerances vs PROJ, in the target CRS's native
/// units. Each adapter states its own measured numbers (see the adapter's
/// crate docs for the measurement).
#[derive(Debug, Clone, Copy)]
pub(crate) struct Tolerances {
    /// Max |Δ| in degrees when the target CRS is geographic.
    pub(crate) degrees: f64,
    /// Max |Δ| in meters when the target CRS is projected.
    pub(crate) meters: f64,
}

impl Tolerances {
    fn for_target(self, to_epsg: u32) -> f64 {
        if to_epsg == 4326 {
            self.degrees
        } else {
            self.meters
        }
    }
}

/// Runs every truth case against `reproject`, asserting agreement with
/// PROJ within `tol`, and returns the worst deviation observed per case
/// (for accuracy reporting). Panics with the offending case/point on any
/// violation.
pub(crate) fn run_truth_suite(reproject: &dyn Reproject, tol: Tolerances) -> Vec<(String, f64)> {
    let table = load_truth();
    assert!(
        !table.cases.is_empty(),
        "empty truth table (provenance: {})",
        table.provenance
    );
    let mut report = Vec::new();
    for case in &table.cases {
        let t = reproject
            .transformer(Crs::from_epsg(case.from_epsg), Crs::from_epsg(case.to_epsg))
            .unwrap_or_else(|e| panic!("{}: transformer failed: {e}", case.name));
        let limit = tol.for_target(case.to_epsg);
        let mut worst = 0.0_f64;
        for (input, expected) in case.input.iter().zip(&case.expected) {
            let (x, y) = t
                .transform(input[0], input[1])
                .unwrap_or_else(|e| panic!("{}: transform({input:?}) failed: {e}", case.name));
            let dev = (x - expected[0]).abs().max((y - expected[1]).abs());
            assert!(
                dev <= limit,
                "{}: point {input:?} -> ({x}, {y}), PROJ says {expected:?}: \
                 deviation {dev:e} exceeds tolerance {limit:e}",
                case.name
            );
            worst = worst.max(dev);
        }
        report.push((case.name.clone(), worst));
    }
    report
}

/// Asserts the adapter's batch path is observably identical to its
/// per-point path on every truth-table input.
pub(crate) fn assert_batch_matches_per_point(reproject: &dyn Reproject) {
    let table = load_truth();
    for case in &table.cases {
        let t = reproject
            .transformer(Crs::from_epsg(case.from_epsg), Crs::from_epsg(case.to_epsg))
            .expect("transformer");
        let mut batch: Vec<(f64, f64)> = case.input.iter().map(|p| (p[0], p[1])).collect();
        t.transform_slice(&mut batch)
            .unwrap_or_else(|e| panic!("{}: batch transform failed: {e}", case.name));
        for (input, &(bx, by)) in case.input.iter().zip(&batch) {
            let (px, py) = t
                .transform(input[0], input[1])
                .expect("per-point transform");
            assert!(
                px.to_bits() == bx.to_bits() && py.to_bits() == by.to_bits(),
                "{}: batch ({bx}, {by}) != per-point ({px}, {py}) for {input:?}",
                case.name
            );
        }
    }
}
