// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! `read_window()` against the numpy truth table — the oracle obligation
//! from docs/EXTENDING.md, discharged for the walkthrough toy (issue #125).
//!
//! `tests/data/window_truth.json` is generated by
//! `tests/oracle/inmem_truth.py` (pinned numpy) from the demo raster's
//! documented value formula. Comparison is EXACT: the SHA-256 of the
//! little-endian pixel bytes must match numpy's byte-for-byte. Provenance
//! is validated as *real* copies: ranges lie within the buffer,
//! `bytes_read` is their sum, and the row-touch count matches the window
//! geometry. The port's error taxonomy is pinned alongside.

use swath_core::raster::{AssetRef, DType, WindowRequest};
use swath_core::source::{BandSelection, RasterSource, ReadLevel, SourceError, WindowData};
use swath_source_inmem::InMemSource;
use swath_testsupport::truth::{self, PixelCase, Truth};

/// Per-source key on top of the shared pixel-identity block.
#[derive(serde::Deserialize)]
struct Case {
    asset: String,
    #[serde(flatten)]
    px: PixelCase,
}

fn truth() -> Truth<Case> {
    truth::load(include_str!("data/window_truth.json"))
}

fn check_case(case: &Case, wd: &WindowData) {
    let name = format!("{}/{}", case.asset, case.px.window_name);

    // The demo grid's only dtype.
    assert_eq!(case.px.dtype, "uint8", "{name}: truth dtype");
    assert_eq!(wd.dtype(), DType::UInt8, "{name}: dtype");
    // EXACT pixel equality with numpy: hash of raw little-endian bytes.
    truth::assert_pixels_match(&name, &case.px, wd);

    // Provenance is real I/O: one in-bounds range per touched row, and
    // bytes_read is their sum.
    let buffer_len = wd.grid.width * wd.grid.height;
    assert_eq!(
        wd.provenance.len(),
        usize::try_from(wd.window.height).expect("tiny grid"),
        "{name}: one provenance range per touched row"
    );
    for p in &wd.provenance {
        assert_eq!(p.path, case.asset, "{name}: provenance path");
        assert!(p.length > 0, "{name}: zero-length provenance range");
        assert!(
            p.offset + p.length <= buffer_len,
            "{name}: provenance range {}+{} exceeds buffer size {buffer_len}",
            p.offset,
            p.length
        );
    }
    let sum: u64 = wd.provenance.iter().map(|p| p.length).sum();
    assert_eq!(wd.bytes_read, sum, "{name}: bytes_read != sum of ranges");
}

#[tokio::test]
async fn windows_match_numpy_truth_exactly() {
    let source = InMemSource::demo();
    let cases = truth().cases;
    assert_eq!(cases.len(), 4, "truth table shrank unexpectedly");
    for case in &cases {
        let wd = source
            .read_window(
                &AssetRef::new(&case.asset),
                case.px.requested.into(),
                BandSelection::Single(0),
                ReadLevel::FullRes,
            )
            .await
            .expect("windowed read succeeds");
        check_case(case, &wd);
    }
}

#[tokio::test]
async fn describe_reports_the_documented_grid() {
    let source = InMemSource::demo();
    let info = source
        .describe(&AssetRef::new("inmem:demo"))
        .await
        .expect("describe succeeds");
    assert_eq!((info.width, info.height), (6, 4));
    assert_eq!(info.band_count, 1);
    assert_eq!(info.dtype, DType::UInt8);
    assert_eq!(info.nodata, Some(255.0));
    assert!(info.overview_levels.is_empty(), "no overviews by design");
}

#[tokio::test]
async fn error_taxonomy_is_the_ports() {
    let source = InMemSource::demo();
    let demo = AssetRef::new("inmem:demo");
    let window = WindowRequest {
        col_off: 0,
        row_off: 0,
        width: 1,
        height: 1,
    };

    let err = source
        .describe(&AssetRef::new("inmem:missing"))
        .await
        .expect_err("unknown asset");
    assert!(matches!(err, SourceError::NotFound { .. }), "{err}");

    let err = source
        .read_window(&demo, window, BandSelection::Single(7), ReadLevel::FullRes)
        .await
        .expect_err("band out of range");
    assert!(
        matches!(err, SourceError::BandOutOfRange { band: 7, .. }),
        "{err}"
    );

    let err = source
        .read_window(
            &demo,
            window,
            BandSelection::Single(0),
            ReadLevel::Overview { factor: 2 },
        )
        .await
        .expect_err("no overviews");
    assert!(
        matches!(err, SourceError::OverviewNotFound { factor: 2, .. }),
        "{err}"
    );
}

#[test]
fn handles_recognizes_the_inmem_scheme() {
    assert!(InMemSource::handles(&AssetRef::new("inmem:demo")));
    assert!(!InMemSource::handles(&AssetRef::new("granule.tif")));
    assert!(!InMemSource::handles(&AssetRef::new(
        "a.vmanifest.json#array"
    )));
}
