// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

/**
 * WebMercatorQuad (slippy-map) tile math shared by the web components
 * (issue #106) — the single home for lon/lat ↔ tile conversions on the
 * frontend, mirroring the server-side TMS math (swath-core `tile.rs`).
 *
 * Oracled the same way the Rust side is: `tms.test.ts` asserts these
 * functions against `tms_truth.json`, a committed morecantile truth table
 * generated by `tests/oracle/tms_truth_web.py` (`just tms-truth-web` to
 * regenerate; the committed JSON, not morecantile-at-HEAD, is what CI sees).
 */

/** Deepest tile level the components address (WebMercatorQuad's usual cap). */
const MAX_ZOOM = 22;

/** Web Mercator's latitude limit, atan(sinh(π)) in degrees at full double
 * precision; inputs are clamped to it, matching morecantile's clamp-to-bbox
 * behavior for poleward points. (A truncated 85.0511 put the pole one-plus
 * rows into the grid at z22 — caught by the truth table.) */
const MAX_MERCATOR_LAT = (Math.atan(Math.sinh(Math.PI)) * 180) / Math.PI;

/**
 * Slippy/WebMercatorQuad tile containing (lon, lat) at the zoom's integer
 * level. Fractional zooms round to the nearest level; zoom is clamped to
 * [0, 22] and latitude to the Web Mercator limit, so any real map view maps
 * to a valid tile address.
 */
export function centerTile(
  lon: number,
  lat: number,
  zoom: number,
): { z: number; x: number; y: number } {
  const z = Math.max(0, Math.min(MAX_ZOOM, Math.round(zoom)));
  const n = 2 ** z;
  const clampedLat = Math.max(-MAX_MERCATOR_LAT, Math.min(MAX_MERCATOR_LAT, lat));
  const latRad = (clampedLat * Math.PI) / 180;
  const x = Math.min(n - 1, Math.max(0, Math.floor(((lon + 180) / 360) * n)));
  const y = Math.min(
    n - 1,
    Math.max(
      0,
      Math.floor(((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2) * n),
    ),
  );
  return { z, x, y };
}

/**
 * Northwest corner of Web Mercator tile `z/x/y` in lon/lat degrees (the
 * standard slippy-map inverse). The southeast corner is the northwest of
 * `z/x+1/y+1`.
 */
export function tileNorthWest(z: number, x: number, y: number): [number, number] {
  const n = 2 ** z;
  const lon = (x / n) * 360 - 180;
  const lat = (Math.atan(Math.sinh(Math.PI * (1 - (2 * y) / n))) * 180) / Math.PI;
  return [lon, lat];
}
