// SPDX-FileCopyrightText: 2026 Elliott Richerson <elliott.richerson@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! `read_window()` against the h5py truth table (issue #39, ADR 0002).
//!
//! `tests/data/window_truth.json` is generated by the fixture maker
//! (`swath-referencer/tests/data/make_tiny_fixture.py`) straight from
//! h5py reads of the committed fixture. Comparison is EXACT: the SHA-256
//! of the little-endian pixel bytes must match h5py's read
//! byte-for-byte — including nodata passthrough and unallocated-chunk
//! fill. Provenance is validated as *real* byte ranges into the ORIGINAL
//! granule: every range is one of the manifest's chunk refs into
//! `tiny.h5` (the legacy thesis, asserted in CI), and lies within the
//! file.

mod common;

use sha2::{Digest, Sha256};
use swath_core::raster::WindowRequest;
use swath_core::source::{
    BandSelection, PixelBuffer, RasterSource, ReadLevel, SourceError, WindowData,
};

#[derive(serde::Deserialize)]
struct Truth {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    array: String,
    window_name: String,
    requested: Win,
    clipped: Win,
    dtype: String,
    nodata: f64,
    nodata_count: u64,
    valid_sum: i64,
    first8: Vec<i64>,
    last8: Vec<i64>,
    sha256_le: String,
}

#[derive(serde::Deserialize, PartialEq, Eq, Debug, Clone, Copy)]
struct Win {
    col_off: u64,
    row_off: u64,
    width: u64,
    height: u64,
}

impl From<Win> for WindowRequest {
    fn from(w: Win) -> Self {
        Self {
            col_off: w.col_off,
            row_off: w.row_off,
            width: w.width,
            height: w.height,
        }
    }
}

fn truth() -> Truth {
    let raw = include_str!("data/window_truth.json");
    serde_json::from_str(raw).expect("window_truth.json parses")
}

fn widened(pixels: &PixelBuffer) -> Vec<i64> {
    match pixels {
        PixelBuffer::Int16(v) => v.iter().map(|&s| i64::from(s)).collect(),
        other => panic!("unexpected pixel dtype in fixture: {:?}", other.dtype()),
    }
}

#[allow(
    clippy::cast_possible_truncation,
    reason = "nodata sentinels are exact small integers"
)]
fn check_case(case: &Case, wd: &WindowData) {
    let name = format!("{}/{}", case.array, case.window_name);

    assert_eq!(wd.window, case.clipped.into(), "{name}: clipped window");
    assert_eq!(case.dtype, "int16", "{name}: truth dtype");
    assert_eq!(wd.nodata, Some(case.nodata), "{name}: nodata sentinel");
    let expected_len = usize::try_from(wd.window.width * wd.window.height).unwrap();
    assert_eq!(wd.pixels.len(), expected_len, "{name}: pixel count");

    // EXACT pixel equality with h5py: hash of raw little-endian bytes.
    let hash = format!("{:x}", Sha256::digest(wd.pixels.to_le_bytes()));
    assert_eq!(hash, case.sha256_le, "{name}: pixel bytes differ from h5py");

    // Redundant with the hash, but failure output is far more diagnostic.
    let samples = widened(&wd.pixels);
    let sentinel = case.nodata as i64;
    let nodata_count = samples.iter().filter(|&&s| s == sentinel).count() as u64;
    let valid_sum: i64 = samples.iter().filter(|&&s| s != sentinel).sum();
    assert_eq!(nodata_count, case.nodata_count, "{name}: nodata count");
    assert_eq!(valid_sum, case.valid_sum, "{name}: valid-pixel sum");
    let first: Vec<i64> = samples.iter().take(8).copied().collect();
    let last: Vec<i64> = samples.iter().rev().take(8).rev().copied().collect();
    assert_eq!(first, case.first8, "{name}: first samples");
    assert_eq!(last, case.last8, "{name}: last samples");
}

#[tokio::test]
async fn windows_match_h5py_truth_exactly() {
    let source = common::memory_source().await;
    let cases = truth().cases;
    assert_eq!(cases.len(), 7, "truth table shrank unexpectedly");
    for case in &cases {
        let wd = source
            .read_window(
                &common::asset(&case.array),
                case.requested.into(),
                BandSelection::Single(0),
                ReadLevel::FullRes,
            )
            .await
            .unwrap_or_else(|e| panic!("{}/{}: {e}", case.array, case.window_name));
        check_case(case, &wd);
    }
}

/// Provenance is the legacy thesis in CI: every byte range a window read
/// points at the ORIGINAL `.h5` (never the manifest), corresponds
/// one-for-one to a manifest chunk ref of the addressed array, and lies
/// within the original file's bounds. `bytes_read` is their sum.
#[tokio::test]
async fn provenance_ranges_are_manifest_chunk_refs_into_the_original_file() {
    let source = common::memory_source().await;
    let manifest = common::generate_manifest();
    let file_len = common::granule_len();
    for case in &truth().cases {
        let wd = source
            .read_window(
                &common::asset(&case.array),
                case.requested.into(),
                BandSelection::Single(0),
                ReadLevel::FullRes,
            )
            .await
            .unwrap();
        let refs: Vec<_> = manifest
            .arrays
            .iter()
            .find(|a| a.name == case.array)
            .expect("array in manifest")
            .refs
            .iter()
            .map(|r| (r.offset, r.length))
            .collect();
        assert!(
            !wd.provenance.is_empty(),
            "{}/{}: a non-empty window reads real ranges",
            case.array,
            case.window_name
        );
        for range in &wd.provenance {
            assert_eq!(
                range.path,
                common::GRANULE_KEY,
                "provenance points at the original granule, not the manifest"
            );
            assert!(
                range.offset + range.length <= file_len,
                "range {}+{} exceeds the original file ({file_len} bytes)",
                range.offset,
                range.length
            );
            assert!(
                refs.contains(&(range.offset, range.length)),
                "range {}+{} is not one of the manifest's chunk refs",
                range.offset,
                range.length
            );
        }
        let total: u64 = wd.provenance.iter().map(|p| p.length).sum();
        assert_eq!(wd.bytes_read, total, "bytes_read is the provenance sum");
    }
}

/// A one-chunk window fetches exactly one chunk range; the full window
/// fetches every allocated chunk (6 for nir, 4 for red — red's third
/// chunk row was never written and costs no I/O).
#[tokio::test]
async fn only_needed_chunks_are_fetched() {
    let source = common::memory_source().await;
    let one = source
        .read_window(
            &common::asset(common::NIR),
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(0),
            ReadLevel::FullRes,
        )
        .await
        .unwrap();
    assert_eq!(one.provenance.len(), 1, "one pixel touches one chunk");

    let full = WindowRequest {
        col_off: 0,
        row_off: 0,
        width: 7,
        height: 8,
    };
    let nir = source
        .read_window(
            &common::asset(common::NIR),
            full,
            BandSelection::Single(0),
            ReadLevel::FullRes,
        )
        .await
        .unwrap();
    assert_eq!(
        nir.provenance.len(),
        6,
        "nir: 3x2 chunk grid fully allocated"
    );
    let red = source
        .read_window(
            &common::asset(common::RED),
            full,
            BandSelection::Single(0),
            ReadLevel::FullRes,
        )
        .await
        .unwrap();
    assert_eq!(
        red.provenance.len(),
        4,
        "red: unallocated chunks cost no I/O"
    );
}

#[tokio::test]
async fn off_grid_windows_clip_to_empty_and_bad_bands_error() {
    let source = common::memory_source().await;
    let wd = source
        .read_window(
            &common::asset(common::NIR),
            WindowRequest {
                col_off: 100,
                row_off: 100,
                width: 4,
                height: 4,
            },
            BandSelection::Single(0),
            ReadLevel::FullRes,
        )
        .await
        .unwrap();
    assert!(wd.window.is_empty());
    assert!(wd.pixels.is_empty());
    assert!(wd.provenance.is_empty());
    assert_eq!(wd.bytes_read, 0);

    let err = source
        .read_window(
            &common::asset(common::NIR),
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(1),
            ReadLevel::FullRes,
        )
        .await
        .unwrap_err();
    assert!(matches!(
        err,
        SourceError::BandOutOfRange {
            band: 1,
            band_count: 1,
            ..
        }
    ));
}

/// Virtual cubes have no overview pyramids: an overview-level read is the
/// port's `OverviewNotFound` error (with an empty available list), never a
/// silent full-resolution serve.
#[tokio::test]
async fn overview_reads_error_cleanly() {
    let source = common::memory_source().await;
    let err = source
        .read_window(
            &common::asset(common::NIR),
            WindowRequest {
                col_off: 0,
                row_off: 0,
                width: 1,
                height: 1,
            },
            BandSelection::Single(0),
            ReadLevel::Overview { factor: 2 },
        )
        .await
        .unwrap_err();
    assert!(
        matches!(
            &err,
            SourceError::OverviewNotFound { factor: 2, available, .. } if available.is_empty()
        ),
        "{err}"
    );
}
